project:
  type: website
  output-dir: docs
bibliography: powersim.bib
csl: apa.csl
website:
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "R version"
        file: index.qmd
      - text: "Python version"
        file: python.qmd
      - text: "Julia version"
        file: julia.qmd
      - text: "Old R version"
        file: index_old.qmd